---
layout: cv
title: Jurnie Crawford's CV 
---

# Jurnie Crawford
**Business Analyst | Student**

<div id="webaddress">
<a href="https://www.linkedin.com/in/jurnie-c-bb3b49119/">My LinkedIn</a>
</div>

---

## Skills
* **SQL** • **Power BI** • **Spreadsheet Analysis** • **Meta Business Suite** • **RStudio**
* **Data Tools:** Python (Polars), Statistical Modeling (ANOVA), Data Cleaning

## Education
### Brigham Young University - Idaho | Rexburg, ID
* **Related Courses:** Business Spreadsheets, Intro to Databases, SQL for Analysts, Financial Accounting, Finance Management, Intermediate Statistics.

## Experience

### Marketing Intern | Sept 2024 - Nov 2024
**Alliance Home Health and Hospice** | *Idaho Falls, ID*
* Built a **Google Sheets tracking system** to reduce duplicate doctor office visits by **20-30%**, enabling outreach to new offices and expanding referral sources.
* Coordinated with facilities management to schedule **3 community events** at assisted living centers; one led to a recurring monthly partnership and expanded outreach opportunities.
* Maximized a **$600/month budget** to support multiple outreach initiatives, enabling events to strengthen community ties.

### Train Agent/Station Master (Seasonal) | April 2021 - Sept 2023
**White Pass Yukon Route Railroad** | *Skagway, AK*
* Coordinated **20+ tour guides daily** to assigned train cars, driving consistent, timely departures.
* Utilized **Microsoft Excel** to design and plan daily boarding and seating plans for up to **2,000 passengers**, balancing ADA individuals and tour directors to ensure a timely departure.
* Reviewed **50+ dispatch schedules per day**, guaranteeing precise tour-to-train coordination.

### Social Media Intern | Oct 2021 - Aug 2023
**Allyson Kelly Associates (AKA)** | *Remote*
* Produced **3–5 posts per week** by developing and executing a social media plan that launched AKA’s online presence and increased engagement.
* Designed and optimized social media content to **drive website traffic**, aligning posts with organizational goals and strengthening digital presence.
* Leveraged social media platforms to create a new avenue for client engagement, generating opportunities for outreach and potential partnerships.

---

<!-- ### Footer

Last updated: May 2013 -->